version: '3'
services:

  backend:
    image: "backend:0.0.1"
    container_name: spring
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  frontend:
    image: "frontend:0.0.1"
    container_name: react
    ports:
      - "3000:3000"
    links:
      - backend